//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhungNoiProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Units
    {
        public Units()
        {
            this.Recipe = new HashSet<Recipe>();
        }
    
        public int unitID { get; set; }
        public string unitName { get; set; }
    
        public virtual ICollection<Recipe> Recipe { get; set; }
    }
}
