//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhungNoiProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member : UserExtension
    {
        public Member()
        {
            this.FeedBack = new HashSet<FeedBack>();
            this.Order = new HashSet<Order>();
            this.webpages_Roles = new HashSet<webpages_Roles>();
        }
    
        public int memberId { get; set; }
        public string UserName { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string phoneNumber { get; set; }
        public string address { get; set; }
        public string profilePicture { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<System.DateTime> lastSignInDate { get; set; }
    
        public virtual ICollection<FeedBack> FeedBack { get; set; }
        public virtual ICollection<Order> Order { get; set; }
        public virtual ICollection<webpages_Roles> webpages_Roles { get; set; }
    }
}
