//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhungNoiProjectTests2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.OderDetail = new HashSet<OderDetail>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public double price { get; set; }
    
        public virtual ICollection<OderDetail> OderDetail { get; set; }
    }
}
