//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhungNoiProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OderDetail
    {
        public int detailID { get; set; }
        public int orderID { get; set; }
        public int productID { get; set; }
        public int productQuantity { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
